@host=http://localhost:2000/api
@json = Content-Type: application/json

### 所有用户
GET {{host}}/users

### 所有用户的在线状态
GET {{host}}/users/onlineStatus

### 重置用户密码
PATCH  {{host}}/users/resetPassword
{{json}}

{
    "id": "67f8fd0d98d671b18c6f64fe"
}

### 登录
POST {{host}}/login
{{json}}

{
    "identity": 0,
    "username": "admin",
    "password": "syadmin"
}

### 注册
POST {{host}}/register
{{json}}

{
    "identity": 2,
    "username": "test",
    "password": "syadmin"
}

### 个人信息
GET {{host}}/profile
{{json}}

{
    "Cookie": {
        "jwt":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc4ZmEyYjE2N2MwYjc4ODk0Y2FkMiIsImlhdCI6MTc0NDI3Nzk1NSwiZXhwIjoxNzQ0MzY0MzU1fQ.ojPwshuwjX4Gb4Blf7pi2ISYHg6FElpDfWW4w_usqbA"
    }
}

### 系统相关配置
GET {{host}}/system

### 退出登录
POST {{host}}/logout

### 分类
GET {{host}}/video/categories

### 视频列表
GET {{host}}/video?limit=5&status=normal

### 视频id
GET {{host}}/video/6824b9aa24e7e30728fd0e1f

### 视频分类
GET {{host}}/video?category=计算机&page=1&limit=12


### 视频合并
GET {{host}}/video/merge/402cc288a5bff7d89a684e8b345b7efbd54d5775e811a388a5c52b5d78d304ec.mp4

### 推荐视频
GET {{host}}/video/recommended?page=1&limit=10&status=normal

### 搜索视频分类
GET {{host}}/video/categories?value=computer